### ISSUE TITLE
Does SocialLGN has the corresponding paper?

### ISSUE THREAD

**Issue by Coder-Yu** [leo0481/SocialLGN#1]

**Comment by leo0481** [comment]
Yes, and it is submitted.

**Comment by Coder-Yu** [comment]
Is there a released version of the paper?

**Comment by leo0481** [comment]
Sorry, we haven't released it yet, but we can send it to your email.

**Comment by ZQSong1997** [comment]
Hello, author, I am very interested in your work, but the papers corresponding to these work are not public. Can you share them with me through this email——1796296884@qq.com? Thanks.

**Comment by leo0481** [comment]
> Hello, author, I am very interested in your work, but the papers corresponding to these work are not public. Can you share them with me through this email——[1796296884@qq.com](mailto:1796296884@qq.com)? Thanks.

Thinks for your interest. We updated our README and add the url to the corresponding paper.
