### ISSUE TITLE
Something about the "social network propagation(user embedding)"

### ISSUE THREAD

**Issue by LaLaLaLaLa2020** [leo0481/SocialLGN#2]
https://github.com/leo0481/SocialLGN/blob/f5947d6b3890cb24454f8219941a54f48138eba6/model.py#L139
I noticed that in the "social network propagation(user embedding)",  in every layer,  the social graph is always multiplied by "users_emb",  which means that you only use the one-hop neighbor.  
It might be helpful for you to understand my confusion:
In every layer, the UI graph is multiplied by the embedding of the last layer. That's the propagation rule.
But in your code, the part of "social network propagation(user embedding)", the social graph is always multiplied by "users_emb"(a.k.a., E0), it should be the embedding of the last layer, right?

**Comment by leo0481** [comment]
As you said, in every layer, the UI graph is multiplied by the embedding of the last layer. And "users_emb" is obtained by splitting the "all_emb", which is the output of the last layer. Thus "users_emb" is $e_u^(k)$ not E^0.

**Comment by Suuuuuuuuuuu** [comment]
Hahaha,  my apologies. I only see the part, not the whole.
Thanks for your reply, which is helpful.
